### ISSUE TITLE
Potential crash due to null reference

### ISSUE THREAD

**Issue by Leayal** [logue/NgsPacker#3]
[At this line of the code](https://github.com/logue/NgsPacker/blob/a610a4bdb02a390fa99e6f999334b2a44c316141/NgsPacker/ViewModels/ShellWindowViewModel.cs#L91) will cause crash if there is no setting for `pso2_bin` path. Because `this.localizerService` hasn't been assigned yet, you assigned the field at a later time. Thus, when the program tries to show the dialog, it will cause `NullReferenceException` instead.

From source:
```csharp
if (!File.Exists(Properties.Settings.Default.Pso2BinPath + Path.DirectorySeparatorChar + "pso2.exe"))
{
    // pso.exe存在確認チェック
    _ = ModernWpf.MessageBox.Show(
       this.localizerService.GetLocalizedString("Pso2ExeNotFoundErrorText"), this.localizerService.GetLocalizedString("ErrorTitleText"));

    // 設定ページに遷移
    this.regionManager.RequestNavigate("ContentRegion", Pages["SettingsItem"]);
}

// リージョンマネージャーをインジェクション
this.regionManager = regionManager;

// 多言語サービスをインジェクション
this.localizerService = localizerService;
```

**Comment by logue** [comment]
Thank you for your report. It seems that this process is being done in the constructor.

Various other troubles have occurred, so we are currently rewriting the source code with WinUI, but we will fix it as an emergency release soon.

**Comment by Leayal** [comment]
Thank you for fixing it. I'll close this as it's resolved.
